# This script creates a backup for the connector in the machine in which it is run.
# The files generated by this script will be saved in C:\ConnectorBackup, these files will
# need to be copy to the machine in which you wish to restore the Connector.

# To restore a Connector look at "Sample connector restore script.ps1"

# RUN THIS SCRIPT IN AN ELEVATED POWERSHELL WINDOW
#Requires -RunAsAdministrator

# Save the current location to restore it later
$originalLocation = Get-Location

Write-Host "This is not intended to create a redundant Connector to run in parallel with this Connector. Attempting to do so will cause printing failures. It is only intended to backup a Connector so it can be restored in case of machine failure or moving to another machine." -ForegroundColor Yellow
Write-Host "Press ENTER to continue the backup."
Read-Host

# Create the needed directories
md C:\ConnectorBackup
md C:\ConnectorBackup\Certs
md C:\ConnectorBackup\CloudData
 
# Backup local printers
c:\windows\system32\spool\tools\PrintBrm.exe -B -F C:\ConnectorBackup\printers.brm
 
# Set permissions for certificates
takeown /R /F "C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys"
icacls "C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys" /save c:\ConnectorBackup\certificatePermissions.txt /T /C
icacls "C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys" --% /grant Administrators:(OI)(CI)F /T
 
# Export UP certificates 
cd Cert:\localmachine\PrintProxyStore
Get-ChildItem -Path 'Cert:\localmachine\PrintProxyStore' | Where-Object { $_.hasPrivateKey } | Foreach-Object { Export-PfxCertificate -Cert $_.ThumbPrint -FilePath "C:\ConnectorBackup\Certs\$($_.Subject)" -Password (ConvertTo-SecureString -String 'password' -AsPlainText -Force) }
 
# Export the Connector registry
reg export HKLM\SOFTWARE\Microsoft\UniversalPrint C:\ConnectorBackup\connector.reg
 
# Export the Cloud Data registries
$counter = 0
$allPrinters = Get-ChildItem 'HKLM:\SYSTEM\CurrentControlSet\Control\Print\Printers'
foreach ($printer in $allPrinters) { 
 $counter++
 $RegKeyName = "$($printer.Name)\CloudData"
 $FileName = "C:\ConnectorBackup\CloudData\CloudData$($counter).reg"
 Write-Host $RegKeyName $FileName
 reg export $RegKeyName $FileName
}
 
# Copy Connector config json
copy C:\windows\PrintConnectorSvc\config.json C:\ConnectorBackup\
 
# Copy Custom Mappings
xcopy /S /Y C:\ProgramData\Microsoft\UniversalPrintConnector\CustomPrintTicketMappings\ c:\ConnectorBackup\PrintTicketMappings\

# Restore permissions for certificates
icacls "C:\ProgramData\Microsoft\Crypto\RSA" /restore c:\ConnectorBackup\certificatePermissions.txt

# Restore the original location
Set-Location $originalLocation